### ISSUE TITLE
how to send mail if a hard drives fails

### ISSUE THREAD

**Issue by Akruidenberg** [gregewing/collectd#1]
I need some help to get this container working with smtp. What are the basic steps to get it this working?

**Comment by gregewing** [comment]
A quick google suggests the “Notify Email” plugin. It should be trivial to configure. I’ll investigate if the plugin is available already in the container when I’m at my desk later. In the meantime please read the link below and let me k ow if you get it working. 

https://collectd.org/wiki/index.php/Plugin:Notify_Email

**Comment by gregewing** [comment]
Yep, I've checked and I did in fact need to add a couple of libraries to the Container.  This has been done and the updated container image has been uploaded to docker hub.  

If you edit the collectd.conf file, you will be able to find a Load statement for notify_email and a corresponding configuration section.  Configure these as required and you will be able to send email notifications using that plugin.  

I've not investigated how flexible that plugin is for meeting your specific needs, but I'll leave that up to you.
good luck !

Greg

**Comment by Akruidenberg** [comment]
msmtp is possible with smartmontools, however, i need access to the smartd_warning.sh file located in /usr/share/smartmontools, it's not mounted in the container. How to make it possible? See https://wiki.archlinux.org/index.php/S.M.A.R.T.

**Comment by gregewing** [comment]
Hi,  I've checked on the instances of this container that I have running on my own docker servers and that folder and script are visible on all of them.  The point of this container is that don't need to install smartmontools on the host, it runs in this container.  If you're running it in privileged mode, you will be able to get all the smartmontools features to work because they are installed in the container and have access to the underlying hardware in the host.  

That said, if you are still having trouble you are able to bind mount any specific file or folder from the host into the container using docker 'volume' configuration when starting or creating the container.
